name: Test
on: push

jobs:
  test:
    needs: new_job
    runs-on: ubuntu-latest
    steps:
      - name: Hello Test
        run: echo "Hello"
      - name: clone repo
        uses: actions/checkout@v2

      - name: run scipt
        run: |
          chmod +x ./new.sh
          ./new.sh

      - name: Goodbye Test
        run: echo "Goodbye"

      - name: clone repo again
        run: cat README.md
  new_job:
    runs-on: ubuntu-latest
    steps:
      - name: Hello from new job
        run: echo "Hello from new job"
