name: Test
on: push

jobs:
  test:
    #needs: new_job
    runs-on: ubuntu-latest
    steps:
      - name: Hello Test
        run: echo "Hello"

      - name: clone repo
        uses: actions/checkout@v2

      - name: run scipt
        run: |
          chmod +x ./new.sh
          ./new.sh

      - name: setup
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: ./new.sh

      - name: Goodbye Test
        run: echo "Goodbye"

      - name: clone repo again
        run: cat README.md
  new_job:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Hello from new job
        run: echo "Hello from new job"

      - name: Goodbye from new job
        uses: actions/download-artifact@v4
        with:
          name: my-artifact

  third_job:
    needs: [test, new_job]
    runs-on: ubuntu-latest
    steps:
      - name: Hello from third job
        run: echo "Hello from third job"
